### ISSUE TITLE
Can i make this work with HomeAssistant

### ISSUE THREAD

**Issue by trekker25** [rhomeister/firepi#1]
Hi Ruben,
found your software on the Homey website.

Myself i use Home Assistant and used a P2000 module that scans for incidents on my hometown.

But i also have a brandweerrooster account from my local firefighter station. I would like to use this to turn on lights when i get a pager call. And hope it's more reliable and quick than P2000 scan.

Is this enough to interact with the API or does our station need to have a special account for this? Other option would be if BrandweerRooster App would interact with IFTT, so i could use my phone to sent a trigger to my home automation software. (Other option would be to use the SMS that brandweer rooster is sending, but Apple / iOS doesn't allow IFTT to interact with SMS messages.)

Please let me know and thanks in advance!

**Comment by rhomeister** [comment]
Hi @trekker25,

Thanks for your interest in this project! This project never got out of the prototype stage, so I recommend you have a look at our API instead. When logged in with your credentials, you have access to all incidents that pertain to your account. We have a REST API (polling), but also a Websockets (real-time).

Could you send us an email to helpdesk@brandweerrooster.nl? I'd be happy to send you some instructions.
